spring.application.name=followersService

server.servlet.context-path=/api/followers

spring.neo4j.uri=${NEO4J_URI}
spring.neo4j.authentication.username=${NEO4J_USERNAME}
spring.neo4j.authentication.password=${NEO4J_PASSWORD}

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS}

grpc.client.auth-service.host=${AUTH_SERVICE_GRPC_HOST:auth-service}
grpc.client.auth-service.port=${AUTH_SERVICE_GRPC_PORT:9090}
