// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.31.1
// source: tour.proto

package tour

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TourQueryService_GetPublishedTours_FullMethodName = "/tour.TourQueryService/GetPublishedTours"
	TourQueryService_GetTourById_FullMethodName       = "/tour.TourQueryService/GetTourById"
)

// TourQueryServiceClient is the client API for TourQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TourQueryServiceClient interface {
	GetPublishedTours(ctx context.Context, in *GetPublishedToursRequest, opts ...grpc.CallOption) (*TourListResponse, error)
	GetTourById(ctx context.Context, in *GetTourByIdRequest, opts ...grpc.CallOption) (*TourDetailsResponse, error)
}

type tourQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTourQueryServiceClient(cc grpc.ClientConnInterface) TourQueryServiceClient {
	return &tourQueryServiceClient{cc}
}

func (c *tourQueryServiceClient) GetPublishedTours(ctx context.Context, in *GetPublishedToursRequest, opts ...grpc.CallOption) (*TourListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TourListResponse)
	err := c.cc.Invoke(ctx, TourQueryService_GetPublishedTours_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourQueryServiceClient) GetTourById(ctx context.Context, in *GetTourByIdRequest, opts ...grpc.CallOption) (*TourDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TourDetailsResponse)
	err := c.cc.Invoke(ctx, TourQueryService_GetTourById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TourQueryServiceServer is the server API for TourQueryService service.
// All implementations must embed UnimplementedTourQueryServiceServer
// for forward compatibility.
type TourQueryServiceServer interface {
	GetPublishedTours(context.Context, *GetPublishedToursRequest) (*TourListResponse, error)
	GetTourById(context.Context, *GetTourByIdRequest) (*TourDetailsResponse, error)
	mustEmbedUnimplementedTourQueryServiceServer()
}

// UnimplementedTourQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTourQueryServiceServer struct{}

func (UnimplementedTourQueryServiceServer) GetPublishedTours(context.Context, *GetPublishedToursRequest) (*TourListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPublishedTours not implemented")
}
func (UnimplementedTourQueryServiceServer) GetTourById(context.Context, *GetTourByIdRequest) (*TourDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTourById not implemented")
}
func (UnimplementedTourQueryServiceServer) mustEmbedUnimplementedTourQueryServiceServer() {}
func (UnimplementedTourQueryServiceServer) testEmbeddedByValue()                          {}

// UnsafeTourQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TourQueryServiceServer will
// result in compilation errors.
type UnsafeTourQueryServiceServer interface {
	mustEmbedUnimplementedTourQueryServiceServer()
}

func RegisterTourQueryServiceServer(s grpc.ServiceRegistrar, srv TourQueryServiceServer) {
	// If the following call panics, it indicates UnimplementedTourQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TourQueryService_ServiceDesc, srv)
}

func _TourQueryService_GetPublishedTours_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublishedToursRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourQueryServiceServer).GetPublishedTours(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourQueryService_GetPublishedTours_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourQueryServiceServer).GetPublishedTours(ctx, req.(*GetPublishedToursRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourQueryService_GetTourById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTourByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourQueryServiceServer).GetTourById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourQueryService_GetTourById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourQueryServiceServer).GetTourById(ctx, req.(*GetTourByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TourQueryService_ServiceDesc is the grpc.ServiceDesc for TourQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TourQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tour.TourQueryService",
	HandlerType: (*TourQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPublishedTours",
			Handler:    _TourQueryService_GetPublishedTours_Handler,
		},
		{
			MethodName: "GetTourById",
			Handler:    _TourQueryService_GetTourById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tour.proto",
}
