// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: tour.proto

package tour

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPublishedToursRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Roles         []string               `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublishedToursRequest) Reset() {
	*x = GetPublishedToursRequest{}
	mi := &file_tour_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublishedToursRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublishedToursRequest) ProtoMessage() {}

func (x *GetPublishedToursRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublishedToursRequest.ProtoReflect.Descriptor instead.
func (*GetPublishedToursRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{0}
}

func (x *GetPublishedToursRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetPublishedToursRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type GetTourByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Roles         []string               `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTourByIdRequest) Reset() {
	*x = GetTourByIdRequest{}
	mi := &file_tour_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTourByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTourByIdRequest) ProtoMessage() {}

func (x *GetTourByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTourByIdRequest.ProtoReflect.Descriptor instead.
func (*GetTourByIdRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{1}
}

func (x *GetTourByIdRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *GetTourByIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetTourByIdRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type TourListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tours         []*TourPublic          `protobuf:"bytes,1,rep,name=tours,proto3" json:"tours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TourListResponse) Reset() {
	*x = TourListResponse{}
	mi := &file_tour_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourListResponse) ProtoMessage() {}

func (x *TourListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourListResponse.ProtoReflect.Descriptor instead.
func (*TourListResponse) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{2}
}

func (x *TourListResponse) GetTours() []*TourPublic {
	if x != nil {
		return x.Tours
	}
	return nil
}

type TourDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicView    bool                   `protobuf:"varint,1,opt,name=public_view,json=publicView,proto3" json:"public_view,omitempty"`
	FullTour      *TourFull              `protobuf:"bytes,2,opt,name=full_tour,json=fullTour,proto3" json:"full_tour,omitempty"`
	PublicTour    *TourPublic            `protobuf:"bytes,3,opt,name=public_tour,json=publicTour,proto3" json:"public_tour,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TourDetailsResponse) Reset() {
	*x = TourDetailsResponse{}
	mi := &file_tour_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourDetailsResponse) ProtoMessage() {}

func (x *TourDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourDetailsResponse.ProtoReflect.Descriptor instead.
func (*TourDetailsResponse) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{3}
}

func (x *TourDetailsResponse) GetPublicView() bool {
	if x != nil {
		return x.PublicView
	}
	return false
}

func (x *TourDetailsResponse) GetFullTour() *TourFull {
	if x != nil {
		return x.FullTour
	}
	return nil
}

func (x *TourDetailsResponse) GetPublicTour() *TourPublic {
	if x != nil {
		return x.PublicTour
	}
	return nil
}

type TourFull struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId      string                 `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty    string                 `protobuf:"bytes,5,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Price         float64                `protobuf:"fixed64,8,opt,name=price,proto3" json:"price,omitempty"`
	DistanceKm    float64                `protobuf:"fixed64,9,opt,name=distance_km,json=distanceKm,proto3" json:"distance_km,omitempty"`
	Durations     []*TourDuration        `protobuf:"bytes,10,rep,name=durations,proto3" json:"durations,omitempty"`
	Keypoints     []*Keypoint            `protobuf:"bytes,11,rep,name=keypoints,proto3" json:"keypoints,omitempty"`
	PublishedAt   *string                `protobuf:"bytes,12,opt,name=published_at,json=publishedAt,proto3,oneof" json:"published_at,omitempty"`
	ArchivedAt    *string                `protobuf:"bytes,13,opt,name=archived_at,json=archivedAt,proto3,oneof" json:"archived_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TourFull) Reset() {
	*x = TourFull{}
	mi := &file_tour_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourFull) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourFull) ProtoMessage() {}

func (x *TourFull) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourFull.ProtoReflect.Descriptor instead.
func (*TourFull) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{4}
}

func (x *TourFull) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TourFull) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *TourFull) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TourFull) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TourFull) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *TourFull) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *TourFull) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TourFull) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TourFull) GetDistanceKm() float64 {
	if x != nil {
		return x.DistanceKm
	}
	return 0
}

func (x *TourFull) GetDurations() []*TourDuration {
	if x != nil {
		return x.Durations
	}
	return nil
}

func (x *TourFull) GetKeypoints() []*Keypoint {
	if x != nil {
		return x.Keypoints
	}
	return nil
}

func (x *TourFull) GetPublishedAt() string {
	if x != nil && x.PublishedAt != nil {
		return *x.PublishedAt
	}
	return ""
}

func (x *TourFull) GetArchivedAt() string {
	if x != nil && x.ArchivedAt != nil {
		return *x.ArchivedAt
	}
	return ""
}

func (x *TourFull) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TourFull) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type TourPublic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId      string                 `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty    string                 `protobuf:"bytes,5,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Price         float64                `protobuf:"fixed64,8,opt,name=price,proto3" json:"price,omitempty"`
	DistanceKm    float64                `protobuf:"fixed64,9,opt,name=distance_km,json=distanceKm,proto3" json:"distance_km,omitempty"`
	Durations     []*TourDuration        `protobuf:"bytes,10,rep,name=durations,proto3" json:"durations,omitempty"`
	FirstKeypoint *Keypoint              `protobuf:"bytes,11,opt,name=first_keypoint,json=firstKeypoint,proto3" json:"first_keypoint,omitempty"`
	PublishedAt   *string                `protobuf:"bytes,12,opt,name=published_at,json=publishedAt,proto3,oneof" json:"published_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TourPublic) Reset() {
	*x = TourPublic{}
	mi := &file_tour_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourPublic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourPublic) ProtoMessage() {}

func (x *TourPublic) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourPublic.ProtoReflect.Descriptor instead.
func (*TourPublic) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{5}
}

func (x *TourPublic) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TourPublic) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *TourPublic) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TourPublic) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TourPublic) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *TourPublic) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *TourPublic) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TourPublic) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TourPublic) GetDistanceKm() float64 {
	if x != nil {
		return x.DistanceKm
	}
	return 0
}

func (x *TourPublic) GetDurations() []*TourDuration {
	if x != nil {
		return x.Durations
	}
	return nil
}

func (x *TourPublic) GetFirstKeypoint() *Keypoint {
	if x != nil {
		return x.FirstKeypoint
	}
	return nil
}

func (x *TourPublic) GetPublishedAt() string {
	if x != nil && x.PublishedAt != nil {
		return *x.PublishedAt
	}
	return ""
}

type TourDuration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransportType string                 `protobuf:"bytes,1,opt,name=transport_type,json=transportType,proto3" json:"transport_type,omitempty"`
	Minutes       int32                  `protobuf:"varint,2,opt,name=minutes,proto3" json:"minutes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TourDuration) Reset() {
	*x = TourDuration{}
	mi := &file_tour_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourDuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourDuration) ProtoMessage() {}

func (x *TourDuration) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourDuration.ProtoReflect.Descriptor instead.
func (*TourDuration) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{6}
}

func (x *TourDuration) GetTransportType() string {
	if x != nil {
		return x.TransportType
	}
	return ""
}

func (x *TourDuration) GetMinutes() int32 {
	if x != nil {
		return x.Minutes
	}
	return 0
}

type Keypoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Latitude      float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Keypoint) Reset() {
	*x = Keypoint{}
	mi := &file_tour_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Keypoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Keypoint) ProtoMessage() {}

func (x *Keypoint) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Keypoint.ProtoReflect.Descriptor instead.
func (*Keypoint) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{7}
}

func (x *Keypoint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Keypoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Keypoint) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Keypoint) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Keypoint) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Keypoint) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type StartExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	TouristId     string                 `protobuf:"bytes,2,opt,name=tourist_id,json=touristId,proto3" json:"tourist_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartExecutionRequest) Reset() {
	*x = StartExecutionRequest{}
	mi := &file_tour_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartExecutionRequest) ProtoMessage() {}

func (x *StartExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartExecutionRequest.ProtoReflect.Descriptor instead.
func (*StartExecutionRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{8}
}

func (x *StartExecutionRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *StartExecutionRequest) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

func (x *StartExecutionRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *StartExecutionRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type GetActiveExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     string                 `protobuf:"bytes,1,opt,name=tourist_id,json=touristId,proto3" json:"tourist_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveExecutionRequest) Reset() {
	*x = GetActiveExecutionRequest{}
	mi := &file_tour_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveExecutionRequest) ProtoMessage() {}

func (x *GetActiveExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveExecutionRequest.ProtoReflect.Descriptor instead.
func (*GetActiveExecutionRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{9}
}

func (x *GetActiveExecutionRequest) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

type VisitedKeypointMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeypointId    string                 `protobuf:"bytes,1,opt,name=keypoint_id,json=keypointId,proto3" json:"keypoint_id,omitempty"`
	VisitedAt     string                 `protobuf:"bytes,2,opt,name=visited_at,json=visitedAt,proto3" json:"visited_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitedKeypointMessage) Reset() {
	*x = VisitedKeypointMessage{}
	mi := &file_tour_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitedKeypointMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitedKeypointMessage) ProtoMessage() {}

func (x *VisitedKeypointMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitedKeypointMessage.ProtoReflect.Descriptor instead.
func (*VisitedKeypointMessage) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{10}
}

func (x *VisitedKeypointMessage) GetKeypointId() string {
	if x != nil {
		return x.KeypointId
	}
	return ""
}

func (x *VisitedKeypointMessage) GetVisitedAt() string {
	if x != nil {
		return x.VisitedAt
	}
	return ""
}

type TourExecutionMessage struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	Id               string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TourId           string                    `protobuf:"bytes,2,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	TouristId        string                    `protobuf:"bytes,3,opt,name=tourist_id,json=touristId,proto3" json:"tourist_id,omitempty"`
	Status           string                    `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt        string                    `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt      *string                   `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	AbandonedAt      *string                   `protobuf:"bytes,7,opt,name=abandoned_at,json=abandonedAt,proto3,oneof" json:"abandoned_at,omitempty"`
	LastActivityAt   string                    `protobuf:"bytes,8,opt,name=last_activity_at,json=lastActivityAt,proto3" json:"last_activity_at,omitempty"`
	StartLatitude    float64                   `protobuf:"fixed64,9,opt,name=start_latitude,json=startLatitude,proto3" json:"start_latitude,omitempty"`
	StartLongitude   float64                   `protobuf:"fixed64,10,opt,name=start_longitude,json=startLongitude,proto3" json:"start_longitude,omitempty"`
	VisitedKeypoints []*VisitedKeypointMessage `protobuf:"bytes,11,rep,name=visited_keypoints,json=visitedKeypoints,proto3" json:"visited_keypoints,omitempty"`
	SagaId           *string                   `protobuf:"bytes,12,opt,name=saga_id,json=sagaId,proto3,oneof" json:"saga_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TourExecutionMessage) Reset() {
	*x = TourExecutionMessage{}
	mi := &file_tour_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourExecutionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourExecutionMessage) ProtoMessage() {}

func (x *TourExecutionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourExecutionMessage.ProtoReflect.Descriptor instead.
func (*TourExecutionMessage) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{11}
}

func (x *TourExecutionMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TourExecutionMessage) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *TourExecutionMessage) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

func (x *TourExecutionMessage) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TourExecutionMessage) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *TourExecutionMessage) GetCompletedAt() string {
	if x != nil && x.CompletedAt != nil {
		return *x.CompletedAt
	}
	return ""
}

func (x *TourExecutionMessage) GetAbandonedAt() string {
	if x != nil && x.AbandonedAt != nil {
		return *x.AbandonedAt
	}
	return ""
}

func (x *TourExecutionMessage) GetLastActivityAt() string {
	if x != nil {
		return x.LastActivityAt
	}
	return ""
}

func (x *TourExecutionMessage) GetStartLatitude() float64 {
	if x != nil {
		return x.StartLatitude
	}
	return 0
}

func (x *TourExecutionMessage) GetStartLongitude() float64 {
	if x != nil {
		return x.StartLongitude
	}
	return 0
}

func (x *TourExecutionMessage) GetVisitedKeypoints() []*VisitedKeypointMessage {
	if x != nil {
		return x.VisitedKeypoints
	}
	return nil
}

func (x *TourExecutionMessage) GetSagaId() string {
	if x != nil && x.SagaId != nil {
		return *x.SagaId
	}
	return ""
}

var File_tour_proto protoreflect.FileDescriptor

const file_tour_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"tour.proto\x12\x04tour\"I\n" +
	"\x18GetPublishedToursRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05roles\x18\x02 \x03(\tR\x05roles\"\\\n" +
	"\x12GetTourByIdRequest\x12\x17\n" +
	"\atour_id\x18\x01 \x01(\tR\x06tourId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\":\n" +
	"\x10TourListResponse\x12&\n" +
	"\x05tours\x18\x01 \x03(\v2\x10.tour.TourPublicR\x05tours\"\x96\x01\n" +
	"\x13TourDetailsResponse\x12\x1f\n" +
	"\vpublic_view\x18\x01 \x01(\bR\n" +
	"publicView\x12+\n" +
	"\tfull_tour\x18\x02 \x01(\v2\x0e.tour.TourFullR\bfullTour\x121\n" +
	"\vpublic_tour\x18\x03 \x01(\v2\x10.tour.TourPublicR\n" +
	"publicTour\"\xff\x03\n" +
	"\bTourFull\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\tR\bauthorId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x05 \x01(\tR\n" +
	"difficulty\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x14\n" +
	"\x05price\x18\b \x01(\x01R\x05price\x12\x1f\n" +
	"\vdistance_km\x18\t \x01(\x01R\n" +
	"distanceKm\x120\n" +
	"\tdurations\x18\n" +
	" \x03(\v2\x12.tour.TourDurationR\tdurations\x12,\n" +
	"\tkeypoints\x18\v \x03(\v2\x0e.tour.KeypointR\tkeypoints\x12&\n" +
	"\fpublished_at\x18\f \x01(\tH\x00R\vpublishedAt\x88\x01\x01\x12$\n" +
	"\varchived_at\x18\r \x01(\tH\x01R\n" +
	"archivedAt\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\tR\tupdatedAtB\x0f\n" +
	"\r_published_atB\x0e\n" +
	"\f_archived_at\"\x96\x03\n" +
	"\n" +
	"TourPublic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\tR\bauthorId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x05 \x01(\tR\n" +
	"difficulty\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x14\n" +
	"\x05price\x18\b \x01(\x01R\x05price\x12\x1f\n" +
	"\vdistance_km\x18\t \x01(\x01R\n" +
	"distanceKm\x120\n" +
	"\tdurations\x18\n" +
	" \x03(\v2\x12.tour.TourDurationR\tdurations\x125\n" +
	"\x0efirst_keypoint\x18\v \x01(\v2\x0e.tour.KeypointR\rfirstKeypoint\x12&\n" +
	"\fpublished_at\x18\f \x01(\tH\x00R\vpublishedAt\x88\x01\x01B\x0f\n" +
	"\r_published_at\"O\n" +
	"\fTourDuration\x12%\n" +
	"\x0etransport_type\x18\x01 \x01(\tR\rtransportType\x12\x18\n" +
	"\aminutes\x18\x02 \x01(\x05R\aminutes\"\xa7\x01\n" +
	"\bKeypoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\x12\x1b\n" +
	"\timage_url\x18\x06 \x01(\tR\bimageUrl\"\x89\x01\n" +
	"\x15StartExecutionRequest\x12\x17\n" +
	"\atour_id\x18\x01 \x01(\tR\x06tourId\x12\x1d\n" +
	"\n" +
	"tourist_id\x18\x02 \x01(\tR\ttouristId\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\":\n" +
	"\x19GetActiveExecutionRequest\x12\x1d\n" +
	"\n" +
	"tourist_id\x18\x01 \x01(\tR\ttouristId\"X\n" +
	"\x16VisitedKeypointMessage\x12\x1f\n" +
	"\vkeypoint_id\x18\x01 \x01(\tR\n" +
	"keypointId\x12\x1d\n" +
	"\n" +
	"visited_at\x18\x02 \x01(\tR\tvisitedAt\"\xf6\x03\n" +
	"\x14TourExecutionMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atour_id\x18\x02 \x01(\tR\x06tourId\x12\x1d\n" +
	"\n" +
	"tourist_id\x18\x03 \x01(\tR\ttouristId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"started_at\x18\x05 \x01(\tR\tstartedAt\x12&\n" +
	"\fcompleted_at\x18\x06 \x01(\tH\x00R\vcompletedAt\x88\x01\x01\x12&\n" +
	"\fabandoned_at\x18\a \x01(\tH\x01R\vabandonedAt\x88\x01\x01\x12(\n" +
	"\x10last_activity_at\x18\b \x01(\tR\x0elastActivityAt\x12%\n" +
	"\x0estart_latitude\x18\t \x01(\x01R\rstartLatitude\x12'\n" +
	"\x0fstart_longitude\x18\n" +
	" \x01(\x01R\x0estartLongitude\x12I\n" +
	"\x11visited_keypoints\x18\v \x03(\v2\x1c.tour.VisitedKeypointMessageR\x10visitedKeypoints\x12\x1c\n" +
	"\asaga_id\x18\f \x01(\tH\x02R\x06sagaId\x88\x01\x01B\x0f\n" +
	"\r_completed_atB\x0f\n" +
	"\r_abandoned_atB\n" +
	"\n" +
	"\b_saga_id2\xa3\x01\n" +
	"\x10TourQueryService\x12K\n" +
	"\x11GetPublishedTours\x12\x1e.tour.GetPublishedToursRequest\x1a\x16.tour.TourListResponse\x12B\n" +
	"\vGetTourById\x12\x18.tour.GetTourByIdRequest\x1a\x19.tour.TourDetailsResponse2\xb4\x01\n" +
	"\x14TourExecutionService\x12I\n" +
	"\x0eStartExecution\x12\x1b.tour.StartExecutionRequest\x1a\x1a.tour.TourExecutionMessage\x12Q\n" +
	"\x12GetActiveExecution\x12\x1f.tour.GetActiveExecutionRequest\x1a\x1a.tour.TourExecutionMessageB\x17Z\x15api-gateway/grpc/tourb\x06proto3"

var (
	file_tour_proto_rawDescOnce sync.Once
	file_tour_proto_rawDescData []byte
)

func file_tour_proto_rawDescGZIP() []byte {
	file_tour_proto_rawDescOnce.Do(func() {
		file_tour_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tour_proto_rawDesc), len(file_tour_proto_rawDesc)))
	})
	return file_tour_proto_rawDescData
}

var file_tour_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_tour_proto_goTypes = []any{
	(*GetPublishedToursRequest)(nil),  // 0: tour.GetPublishedToursRequest
	(*GetTourByIdRequest)(nil),        // 1: tour.GetTourByIdRequest
	(*TourListResponse)(nil),          // 2: tour.TourListResponse
	(*TourDetailsResponse)(nil),       // 3: tour.TourDetailsResponse
	(*TourFull)(nil),                  // 4: tour.TourFull
	(*TourPublic)(nil),                // 5: tour.TourPublic
	(*TourDuration)(nil),              // 6: tour.TourDuration
	(*Keypoint)(nil),                  // 7: tour.Keypoint
	(*StartExecutionRequest)(nil),     // 8: tour.StartExecutionRequest
	(*GetActiveExecutionRequest)(nil), // 9: tour.GetActiveExecutionRequest
	(*VisitedKeypointMessage)(nil),    // 10: tour.VisitedKeypointMessage
	(*TourExecutionMessage)(nil),      // 11: tour.TourExecutionMessage
}
var file_tour_proto_depIdxs = []int32{
	5,  // 0: tour.TourListResponse.tours:type_name -> tour.TourPublic
	4,  // 1: tour.TourDetailsResponse.full_tour:type_name -> tour.TourFull
	5,  // 2: tour.TourDetailsResponse.public_tour:type_name -> tour.TourPublic
	6,  // 3: tour.TourFull.durations:type_name -> tour.TourDuration
	7,  // 4: tour.TourFull.keypoints:type_name -> tour.Keypoint
	6,  // 5: tour.TourPublic.durations:type_name -> tour.TourDuration
	7,  // 6: tour.TourPublic.first_keypoint:type_name -> tour.Keypoint
	10, // 7: tour.TourExecutionMessage.visited_keypoints:type_name -> tour.VisitedKeypointMessage
	0,  // 8: tour.TourQueryService.GetPublishedTours:input_type -> tour.GetPublishedToursRequest
	1,  // 9: tour.TourQueryService.GetTourById:input_type -> tour.GetTourByIdRequest
	8,  // 10: tour.TourExecutionService.StartExecution:input_type -> tour.StartExecutionRequest
	9,  // 11: tour.TourExecutionService.GetActiveExecution:input_type -> tour.GetActiveExecutionRequest
	2,  // 12: tour.TourQueryService.GetPublishedTours:output_type -> tour.TourListResponse
	3,  // 13: tour.TourQueryService.GetTourById:output_type -> tour.TourDetailsResponse
	11, // 14: tour.TourExecutionService.StartExecution:output_type -> tour.TourExecutionMessage
	11, // 15: tour.TourExecutionService.GetActiveExecution:output_type -> tour.TourExecutionMessage
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_tour_proto_init() }
func file_tour_proto_init() {
	if File_tour_proto != nil {
		return
	}
	file_tour_proto_msgTypes[4].OneofWrappers = []any{}
	file_tour_proto_msgTypes[5].OneofWrappers = []any{}
	file_tour_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tour_proto_rawDesc), len(file_tour_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_tour_proto_goTypes,
		DependencyIndexes: file_tour_proto_depIdxs,
		MessageInfos:      file_tour_proto_msgTypes,
	}.Build()
	File_tour_proto = out.File
	file_tour_proto_goTypes = nil
	file_tour_proto_depIdxs = nil
}
