spring.application.name=stakeholdersService

spring.neo4j.uri=${SPRING_NEO4J_URI}
spring.neo4j.authentication.username=${SPRING_NEO4J_AUTHENTICATION_USERNAME}
spring.neo4j.authentication.password=${SPRING_NEO4J_AUTHENTICATION_PASSWORD}