spring.application.name=stakeholdersService

server.servlet.context-path=/api/stakeholders

spring.neo4j.uri=${SPRING_NEO4J_URI}
spring.neo4j.authentication.username=${SPRING_NEO4J_AUTHENTICATION_USERNAME}
spring.neo4j.authentication.password=${SPRING_NEO4J_AUTHENTICATION_PASSWORD}

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS}