spring.application.name=auth-service

server.servlet.context-path=/api/auth

spring.neo4j.uri=${NEO4J_URI}
spring.neo4j.authentication.username=${NEO4J_USERNAME}
spring.neo4j.authentication.password=${NEO4J_PASSWORD}

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS}
stakeholders.service.url=${STAKEHOLDERS_SERVICE_URL:http://stakeholders-service:8080/api/stakeholders}

grpc.server.port=${GRPC_SERVER_PORT:9090}

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
management.otlp.metrics.export.enabled=false

management.tracing.sampling.probability=1.0
management.opentelemetry.tracing.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:http://tempo:4318/v1/traces}

logging.pattern.console=%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} level=%-5level service=auth-service logger=%logger{36} otelTraceID=%X{traceId:-00000000000000000000000000000000} otelSpanID=%X{spanId:-0000000000000000} message=%msg%n
logging.level.com.soa.authService=INFO