spring.application.name=authService

server.servlet.context-path=/api/auth

spring.neo4j.uri=${NEO4J_URI}
spring.neo4j.authentication.username=${NEO4J_USERNAME}
spring.neo4j.authentication.password=${NEO4J_PASSWORD}

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS}
stakeholders.service.url=${STAKEHOLDERS_SERVICE_URL:http://stakeholders-service:8080/api/stakeholders}

grpc.server.port=${GRPC_SERVER_PORT:9090}